scripts = [
    'ntsynt_pipeline.py',
    'Snakefile',
    'extract_synteny_regions.py',
    'plot_dists.R',
    'analyze_mx.py',
    'denovo_synteny_block_stats.py',
    'kmc_find_common_kmers.sh',
    'generate_report.py',
    'phylogeny.smk',
    'rename_newick.py',
    'run_phylogeny.py',
]

install_data(scripts, install_dir : 'bin')
